require(['config'],function(){
    require(['jquery','footer','return','zoom','lunbo'],function($,foo,re,zoom){
        $('footer').load('../html/footer.html',function(){
            foo();
        });
        $('.returnT').load('../html/return.html',function(){
            re();
        });
        $('header').load('../html/header.html')

        $('nav').load('../html/nav.html')
        $id=window.location.search.slice(1).split('=')[1]*1;
        $.ajax({
            url:'../MySQL/good.php',
            data:{
                id:$id,
            },
            dataType:'json',
            success:function(data){
                $('.title')[0].innerText=data.class+data.name+data.engname;
                $('.zan')[0].innerText="（已有"+data.saled+"口碑）";
                $('.np')[0].innerText=data.nprice;
                $('.dc')[0].innerText=data.discount+"折";
                $('.econ')[0].innerText=data.nprice/data.discount*10-data.nprice;
                $('.op')[0].innerText=data.oprice;
                $('.sp')[0].innerText=data.nprice/data.discount*10;
                $('.send')[0].innerText=data.sendm+"极速直达";
                $('.pic')[0].src=data.url;
                $('.donum').on('click',function(){
                    var num1=$('#addto')[0].value;
                    if(this.innerText=='+'){
                        num1++;
                        $('#addto')[0].value=num1;
                    }else{
                        num1--;
                        if(num1<=1){
                            $('#addto')[0].value=1;
                        }else{
                            $('#addto')[0].value=num1;
                        }
                    }
                })
                $('.addtocar').on('click',function(){
                    var num2=$('#addto')[0].value;
                    $.ajax({
                        url:'../MySQL/addtocar.php',
                        data:{
                            id:data.id,
                            name:data.name,
                            url:data.url,
                            oprice:data.oprice,
                            nprice:data.nprice,
                            qty:num2,
                            sendm:data.sendm,
                            pinpai:data.pinpai
                        },
                        success:function(data){
                            $('#addto')[0].value=1;
                        }
                    })
                })
                $('.details').douZoom({
                    width:427,
                    height:420,
                })
            }
        }) 
    })
});