define(['jquery'],function(){
    return function(){
        $tar=$('.Links').closest('li');
        $tar.on('mouseenter',function(){
            $('.hideNav').stop().animate({height:80})
        }).on('mouseleave',function(){
            $('.hideNav').stop().animate({height:0})
        })
        $('.identity').on('mouseenter',function(){
            $('.identity').stop().css({
                width:127*1.2,
                height:47*1.2,
                left:-127*0.1,
                top:-47*0.1,
            })
        }).on('mouseleave',function(){
            $('.identity').stop().css({
                width:127,
                height:47,
                left:0,
                top:0,
            })
        })
    }
})
