define(['jquery'],function(){
    return function(){
        $(window).on('scroll',function(){
            if($(window).scrollTop()>=600){
                $('#returnTop').find('ul').stop().animate({
                    height:200,
                }) 
            }
            else{
               $('#returnTop').find('ul').stop().animate({
                    height:160,
                }) 
            }
        })
        $('.doreyurn').on('click',function(){
            window.scrollTo(0)
        })
    }
})
